a = input(input("첫 번째 숫자를 입력하세요: "))
b = input(input("두 번째 숫자를 입력하세요: "))
result =a+b
print(a,"+",b,"=",result)
result = a - b
print(a,"-",b,"=",result)
result = a * b
print(a,"*",b,"=",result)
result = a / b
print(a,"/",b,"=",result)
